"""initial-table

Revision ID: 14aa456248b5
Revises: 
Create Date: 2026-02-02 20:55:56.304708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aa456248b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('localidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('regiao', sa.String(length=30), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('ibge', sa.String(length=7), nullable=True),
    sa.Column('gia', sa.String(length=4), nullable=True),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('siafi', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cep')
    # ### end Alembic commands ###
