"""add updated_at to cep

Revision ID: 8bb0eeb1079f
Revises: 14aa456248b5
Create Date: 2026-02-06 09:08:49.475430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb0eeb1079f'
down_revision = '14aa456248b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cep', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
