"""tabela cep

Revision ID: cc4a9be05da4
Revises: 
Create Date: 2026-01-26 13:37:25.160482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4a9be05da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regiao', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cep', schema=None) as batch_op:
        batch_op.drop_column('complemento')
        batch_op.drop_column('regiao')

    # ### end Alembic commands ###
